name: "Bump version number"
author: "action-pack"
description: "Action to bump a version number using repository variables."

branding:
  icon: "plus"
  color: "gray-dark"

inputs:
  token:
    description: Repository access token
    required: true

  repository:
    description: Repository name
    default: false
    required: false

  owner:
    description: Repository owner
    default: false
    required: false

  org:
    description: Flag for organization
    default: false
    required: false

runs:
  using: node20
  main: dist/index.js
