name: "Bump version number"
author: "action-pack"
description: "Action to bump a version number using repository variables."

branding:
  icon: "plus"
  color: "gray-dark"

inputs:
  token:
    description: Repository access token
    required: true

  repository:
    description: Repository name
    default: false
    required: false

  owner:
    description: Repository owner
    default: false
    required: false

  org:
    description: Flag for organization
    default: false
    required: false

# runs:
#   using: node16
#   main: dist/index.js

# This part is temporary to enable Node 18 support

runs:
  using: composite
  steps:

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version || '18' }}

    - name: Action
      run: |
        node ${{ github.action_path }}/dist/index.js        
      shell: ${{ (runner.os == 'Windows' && 'pwsh') || 'bash' }}
      env:
        INPUT_OWNER: ${{ inputs.owner }}
        INPUT_ORG: ${{ inputs.org }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
